-- Blood Connect: Supabase database schema

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text not null,
  blood_group text not null check (blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  area text default '',
  age int,
  gender text default '',
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists age int;
alter table public.profiles add column if not exists gender text default '';

create table if not exists public.blood_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  patient_name text not null,
  blood_group text not null check (blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  blood_required text,
  units int not null check (units > 0),
  hospital text not null,
  requester_phone text,
  status text not null default 'open' check (status in ('open','accepted','fulfilled','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.blood_requests add column if not exists requester_phone text;
alter table public.blood_requests add column if not exists blood_required text;
update public.blood_requests
set blood_required = blood_group
where blood_required is null;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  subtitle text not null,
  type text not null default 'system' check (type in ('system','blood_request','campaign')),
  created_at timestamptz not null default now()
);

create index if not exists idx_profiles_group_available
  on public.profiles (blood_group, available);

create index if not exists idx_requests_user_created
  on public.blood_requests (user_id, created_at desc);

create index if not exists idx_notifications_user_created
  on public.notifications (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.blood_requests enable row level security;
alter table public.notifications enable row level security;

-- profiles
drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
on public.profiles
for select
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- blood_requests
drop policy if exists "requests_insert_own" on public.blood_requests;
create policy "requests_insert_own"
on public.blood_requests
for insert
with check (auth.uid() = user_id);

drop policy if exists "requests_select_own" on public.blood_requests;
create policy "requests_select_own"
on public.blood_requests
for select
using (auth.uid() = user_id);

-- notifications
drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
on public.notifications
for select
using (auth.uid() = user_id);

drop policy if exists "notifications_insert_authenticated" on public.notifications;
create policy "notifications_insert_authenticated"
on public.notifications
for insert
to authenticated
with check (true);

drop policy if exists "notifications_delete_authenticated" on public.notifications;
create policy "notifications_delete_authenticated"
on public.notifications
for delete
to authenticated
using (true);

-- Optional: create profile automatically on new auth user
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, blood_group, area, age, gender, available)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce(new.raw_user_meta_data->>'phone', ''),
    coalesce(new.raw_user_meta_data->>'blood_group', 'A+'),
    coalesce(new.raw_user_meta_data->>'area', ''),
    nullif(new.raw_user_meta_data->>'age', '')::int,
    coalesce(new.raw_user_meta_data->>'gender', ''),
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
